"""Mention roles are assertions about a referent, never a lexicon of names."""

MENTION_KINDS = ('external_service', 'product_operation', 'role_description', 'description', 'unclear', 'other')

MENTION_ROLE_INSTRUCTION = (
    'Identify what the exact candidate refers to in this occurrence before choosing its field.\n'
    'Distinguish the identity of the target product, a fact about that product, an action,\n'
    'a compatibility/configuration target, and an outside provider used by the product.\n'
    'The grammatical subject of an action is not itself the action.\n'
    '\n'
    'external_service refers to the named outside provider itself in an explicitly stated\n'
    "integration relationship: the target product uses that provider's authentication,\n"
    'data, communication, payment, or another concrete service. A supported client,\n'
    'compatible platform, or configuration-output target alone does not establish this\n'
    'relationship. A service can be used through an SDK; do not require deployment proof,\n'
    'an API URL, or a particular implementation mechanism. A committed requirement can\n'
    'establish the relationship before implementation. Use the existing dedicated field\n'
    'definitions for operating AI models/APIs, implementation stacks, storage engines,\n'
    'and deployment choices rather than treating every outside name as an integration.\n'
    '\n'
    'product_operation is an explicitly stated action performed by the target product\n'
    "or its users. A product name or a compatibility target's name alone is not an action.\n"
    'role_description describes what a tool/provider is used for, not the provider name.\n'
    'description is a modifier, benefit or tagline, not a named service or operation.\n'
    'Read subject/action/provider relationships in sentences, lists and tables regardless\n'
    'of order. Never copy the provider field onto its purpose. The purpose can support\n'
    'a feature only when its context explicitly establishes a product operation;\n'
    'otherwise preserve the relevant ambiguity as tentative.\n'
    '\n'
    'mentionKind=other covers facts expressed by the remaining Profile fields, including\n'
    'target product identity, delivery form, problem domain, implementation technology,\n'
    'operating AI, storage engine, and deployment environment. These can be current\n'
    'positive product facts: use their actual Profile field and role=product_fact when\n'
    'supported. They are not automatically non_product or irrelevant. A noun phrase that\n'
    'states delivery form or problem domain is not merely description for being descriptive.\n'
    'mentionKind=other is distinct from field=other. The instruction about facts outside\n'
    'the ten fields refers to field=other, not every use of mentionKind=other.\n'
    '\n'
    'Judge every occurrence by its relationship and subject. A name mentioned in another\n'
    'project or an example does not inherit target-project adoption. The same name may\n'
    'be a compatibility target in one occurrence and a consumed provider in another.\n'
    'Use field=other and irrelevant only when the claim is clearly outside all ten fields;\n'
    'do not convert a bare target name into a feature. Preserve an explicit action in\n'
    'features when that candidate and its context actually state the action.\n'
    'Use unclear and tentative for unresolved relevant roles in a plausible field;\n'
    'role uncertainty is not irrelevance. Preserve the existing scope, time, polarity,\n'
    'commitment and status rules. Explicit denial stays negated in the corresponding\n'
    'field; undecided adoption and unresolved conflicts must not become confirmed.\n'
    'Select both sides of a genuine unresolved conflict, and keep unrelated denials\n'
    'separate. Do not infer roles from capitalization, brands, name lists, or typical\n'
    'capabilities. Do not generate user approval.'
)
